version: '2.3'
services:
  mysql:
    image: mysql:5.7.19
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./configuration/mysql/scripts:/docker-entrypoint-initdb.d
    command: [--ssl=0]
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-proot"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  ob-key-manager:
    image: wso2-obkm:1.3.0-base
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:9446/carbon/admin/login.jsp"]
      interval: 10s
      timeout: 120s
      start_period: 100s
      retries: 15
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./configuration/wso2-obkm:/home/wso2carbon/wso2-config-volume
    ports:
      - "9446:9446"
  ob-api-manager:
    image: wso2-obam:1.3.0-base
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:9443/carbon/admin/login.jsp"]
      interval: 10s
      timeout: 120s
      start_period: 100s
      retries: 5
    depends_on:
      mysql:
        condition: service_healthy
      ob-key-manager:
        condition: service_healthy
    volumes:
      - ./configuration/wso2-obam:/home/wso2carbon/wso2-config-volume
    ports:
      - "9443:9443"
      - "8243:8243"
